### ISSUE TITLE
Build fails on Windows 10

### ISSUE THREAD

**Issue by AHandless** [ton-blockchain/wallet-desktop#11]
I followed [these](https://github.com/ton-blockchain/wallet-desktop/blob/master/docs/building-msvc.md) build instructions but ended up not building anything due to an error.
 
```
Logging.cpp
K:\TON-Wallet\Libraries\ton\tonlib\tonlib\Logging.cpp(43): fatal error C1001: An internal error has occurred in the com
piler. [K:\TON-Wallet\Libraries\ton\build-debug\tonlib\tonlib.vcxproj]
  (compiler file 'msc1.cpp', line 1527)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  Please choose the Technical Support command on the Visual C++
   Help menu, or open the Technical Support help file for more information
  Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bi
  n\HostX64\x86\CL.exe.  You will be prompted to send an error report to Microsoft later.
cl : Command line error D8040: error creating or communicating with child process [K:\TON-Wallet\Libraries\ton\build-de
bug\tonlib\tonlib.vcxproj]
```

**Comment by john-preston** [comment]
Maybe you need a newer compiler version? What version of VS2019 are you using?

**Comment by AHandless** [comment]
Yes, the compiler was outdated. Thanks.
Now I get another error in Visual Studio.
```
1>[396/396] LINK_EMBED Wallet.exe
1>FAILED: Wallet.exe Wallet.exe.pdb
1>K:\TON-Wallet\ThirdParty\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True Wallet.exe "K:\TON-Wallet\ThirdParty\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:Wallet.exe @Wallet.exe.rsp" 1 mt.exe rc.exe "obj\Wallet.Wallet.exe.intermediate.manifest" obj\Wallet.Wallet.exe.generated.manifest ..\..\Wallet\Resources\win\Wallet.manifest
1>lib_base.lib(lib_base.crash_report_writer.obj) : error LNK2019: unresolved external symbol "public: __thiscall google_breakpad::ExceptionHandler::ExceptionHandler(class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > const &,bool (__cdecl*)(void *,struct _EXCEPTION_POINTERS *,struct MDRawAssertionInfo *),bool (__cdecl*)(unsigned short const *,unsigned short const *,void *,struct _EXCEPTION_POINTERS *,struct MDRawAssertionInfo *,bool),void *,int,enum _MINIDUMP_TYPE,unsigned short const *,struct google_breakpad::CustomClientInfo const *)" (??0ExceptionHandler@google_breakpad@@QAE@ABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@P6A_NPAXPAU_EXCEPTION_POINTERS@@PAUMDRawAssertionInfo@@@ZP6A_NPBG5123_N@Z1HW4_MINIDUMP_TYPE@@5PBUCustomClientInfo@1@@Z) referenced in function "private: void __thiscall base::CrashReportWriter::startCatching(void)" (?startCatching@CrashReportWriter@base@@AAEXXZ)
1>
1>Wallet.exe : fatal error LNK1120: 1 unresolved externals
1>
1>Traceback (most recent call last):
1>
1>  File "gyp-win-tool", line 327, in <module>
1>
1>    sys.exit(main(sys.argv[1:]))
1>
1>  File "gyp-win-tool", line 31, in main
1>
1>    exit_code = executor.Dispatch(args)
1>
1>  File "gyp-win-tool", line 73, in Dispatch
1>
1>    return getattr(self, method)(*args[1:])
1>
1>  File "gyp-win-tool", line 181, in ExecLinkWithManifests
1>
1>    subprocess.check_call(ldcmd + add_to_ld)
1>
1>  File "K:\TON-Wallet\ThirdParty\Python27\lib\subprocess.py", line 190, in check_call
1>
1>    raise CalledProcessError(retcode, cmd)
1>
1>subprocess.CalledProcessError: Command 'K:\TON-Wallet\ThirdParty\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:Wallet.exe @Wallet.exe.rsp Wallet.exe.manifest.res' returned non-zero exit status 1120
1>
1>ninja: build stopped: cannot make progress due to previous errors.
1>K:\TON-Wallet\wallet-desktop\Wallet\Wallet.vcxproj(204,5): error MSB3073: The command "call ninja.exe -C ..\out\Debug\ -k0 Wallet" exited with code 1.
1>Done building project "Wallet.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by john-preston** [comment]
@AHandless I didn't provide breakpad patch, maybe it'll now build fine, please update or re-clone patches repository:

https://github.com/ton-blockchain/wallet-desktop/commit/b64e67b844f6c25d6aa286c64b3385e902b66187#diff-48ef1a5289c19122254f17d2b14484eeR56

And try clean-building breakpad:

https://github.com/ton-blockchain/wallet-desktop/commit/b64e67b844f6c25d6aa286c64b3385e902b66187#diff-48ef1a5289c19122254f17d2b14484eeR84-R98

**Comment by AleksejMelman** [comment]
Same for me. Took the sources a day ago, compiled all good, but failed with the same error in VS2019.
. . . 
```
1>[395/397] CXX SourceFiles\wallet\Wallet.application.obj
1>[396/397] CXX SourceFiles\core\Wallet.launcher.obj
1>[397/397] LINK_EMBED Wallet.exe
1>FAILED: Wallet.exe Wallet.exe.pdb
1>C:\home\ton_wallet\VisualStudio2019\ThirdParty\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True Wallet.exe "C:\home\ton_wallet\VisualStudio2019\ThirdParty\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:Wallet.exe @Wallet.exe.rsp" 1 mt.exe rc.exe "obj\Wallet.Wallet.exe.intermediate.manifest" obj\Wallet.Wallet.exe.generated.manifest ..\..\Wallet\Resources\win\Wallet.manifest
1>Wallet.update_info_provider.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall Wallet::UpdateInfoProvider::check(void)" (?check@UpdateInfoProvider@Wallet@@UAEXXZ)
1>
1>Wallet.exe : fatal error LNK1120: 1 unresolved externals
1>
1>Traceback (most recent call last):
1>
1>  File "gyp-win-tool", line 327, in <module>
1>
1>    sys.exit(main(sys.argv[1:]))
1>
1>  File "gyp-win-tool", line 31, in main
1>
1>    exit_code = executor.Dispatch(args)
1>
1>  File "gyp-win-tool", line 73, in Dispatch
1>
1>    return getattr(self, method)(*args[1:])
1>
1>  File "gyp-win-tool", line 181, in ExecLinkWithManifests
1>
1>    subprocess.check_call(ldcmd + add_to_ld)
1>
1>  File "C:\home\ton_wallet\VisualStudio2019\ThirdParty\Python27\lib\subprocess.py", line 190, in check_call
1>
1>    raise CalledProcessError(retcode, cmd)
1>
1>subprocess.CalledProcessError: Command 'C:\home\ton_wallet\VisualStudio2019\ThirdParty\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:Wallet.exe @Wallet.exe.rsp Wallet.exe.manifest.res' returned non-zero exit status 1120
1>
1>ninja: build stopped: cannot make progress due to previous errors.
1>C:\home\ton_wallet\VisualStudio2019\wallet-desktop\Wallet\Wallet.vcxproj(204,5): error MSB3073: The command "call ninja.exe -C ..\out\Debug\ -k0 Wallet" exited with code 1.
1>Done building project "Wallet.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
