### ISSUE TITLE
Linux Binary: Segmentation fault 

### ISSUE THREAD

**Issue by HaskuldrKrionskij** [ton-blockchain/wallet-desktop#27]
```
$ gdb -q ./Wallet
BFD: warning: /home/user/.Wallet/Wallet has a corrupt string table index - ignoring
Reading symbols from ./Wallet...
(No debugging symbols found in ./Wallet)
(gdb) run
Starting program: /home/user/.Wallet/Wallet 

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7fde4c1 in _dl_relocate_object () from /lib64/ld-linux-x86-64.so.2
(gdb) backtrace
#0  0x00007ffff7fde4c1 in _dl_relocate_object () from /lib64/ld-linux-x86-64.so.2
#1  0x00007ffff7fd6676 in dl_main () from /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7fec25b in _dl_sysdep_start () from /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff7fd3fdc in _dl_start () from /lib64/ld-linux-x86-64.so.2
#4  0x00007ffff7fd3108 in _start () from /lib64/ld-linux-x86-64.so.2
#5  0x0000000000000001 in ?? ()
#6  0x00007fffffffe2c3 in ?? ()
#7  0x0000000000000000 in ?? ()
```
Write if I need to copy-past anything else.

**Comment by HaskuldrKrionskij** [comment]
Solved: Donwload binary 0.9.7, run and update to 0.9.8.
